# Generated by Django 3.1.2 on 2020-10-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201011_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='oreder_date',
        ),
    ]
