# Generated by Django 3.1.2 on 2020-10-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201011_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_date',
            new_name='order_date',
        ),
    ]
